### ISSUE TITLE
[fyi] Similar userscript, different layout

### ISSUE THREAD

**Issue by realAzazello** [yookibooki/EnginesOnGoogle#1]
Very nice design you have there, thanks for the contrib.

Just wanna shared that [lednerg](https://github.com/lednerg) also created something similar, but didn't release it as a formal script: https://github.com/darkred/Userscripts/issues/55#issuecomment-1504731677. Still working smoothly up to now. You might find some interest in his code.

**Comment by yookibooki** [comment]
Got it. I appreciate your attention
